enum Country {
  "United States" = "US",
  "Canada" = "CA",
  "United Kingdom" = "GB",
  "Germany" = "DE",
  "France" = "FR",
  "Italy" = "IT",
  "Spain" = "ES",
  "Japan" = "JP",
  "China" = "CN",
  "India" = "IN",
  "Brazil" = "BR",
  "Australia" = "AU",
  "Russia" = "RU",
  "South Africa" = "ZA",
  "Mexico" = "MX",
  "Argentina" = "AR",
  "Colombia" = "CO",
  "South Korea" = "KR",
  "Egypt" = "EG",
  "Greece" = "GR",
  "Sweden" = "SE",
  "Norway" = "NO",
  "Netherlands" = "NL",
  "Belgium" = "BE",
  "Switzerland" = "CH",
  "Austria" = "AT",
  "Portugal" = "PT",
  "Denmark" = "DK",
  "Finland" = "FI",
  "United Arab Emirates" = "AE",
  "Saudi Arabia" = "SA",
  "Turkey" = "TR",
  "Iran" = "IR",
  "Israel" = "IL",
}


export default Country